name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar dependencias
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          pip install black ruff pytest pytest-cov pdoc
      - name: Revisar formato (Black)
        run: .venv/bin/black --check src tests
      - name: Revisar estilo (Ruff)
        run: .venv/bin/ruff check src tests
      - name: Ejecutar tests con cobertura
        run: .venv/bin/pytest --cov=src --cov-report=term-missing